---
World: pewPewGame
Locations:
  Spawn:
    X: 0.5
    Y: 0.5
    Z: 0.5
  Loc1:
    X: 0.5
    Y: 0.5
    Z: 0.5
  Loc2:
    X: 0.5
    Y: 0.5
    Z: 0.5
Kills:
  d20c8b3b-9f9e-48da-94c4-2c614dd76e29: 0
Death:
  d20c8b3b-9f9e-48da-94c4-2c614dd76e29: 0